spring:
    jdbc:
        dataSourceList:
            -   driverClassName: com.mysql.jdbc.Driver
                jdbcUrl: jdbc:mysql://127.0.0.1:3306/medical_recruitment?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
                username: medical_recruitment-user
                password: mmmm8888
                dbAlias: recruitment
                mapperScan: com.andy.recruitment.dao.*.mapper
                mapperLocations: classpath:mapper/*/*.xml

executor:
    corePoolSize: 20
    maximumPoolSize: 40
    keepAliveTime: 60000
    queueSize: 1024
    threadName: recruitment-server-thread

weixin:
    appId: wx659743c693dd2f10
    appSecret: e9809618ff58a3b9a1c8704bd9649652
    apiAddress: https://api.weixin.qq.com
    openAddress: https://open.weixin.qq.com